version: 0.2

phases:
  install:
    commands:
      - echo install
      - npm ci
  build:
    commands:
      - echo build
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
